from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Sequence

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    HRFlowable,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

# ---------------------------------------------------------------------------
# Colour palette  (matches ShadowScan dark-UI aesthetic)
# ---------------------------------------------------------------------------
COL_BG = colors.HexColor('#0D1117')
COL_SURFACE = colors.HexColor('#161B22')
COL_BORDER = colors.HexColor('#30363D')
COL_TEXT = colors.HexColor('#E6EDF3')
COL_MUTED = colors.HexColor('#8B949E')
COL_CYAN = colors.HexColor('#22D3EE')
COL_WHITE = colors.HexColor('#FFFFFF')

SEV_CRITICAL = colors.HexColor('#EF4444')
SEV_HIGH = colors.HexColor('#F97316')
SEV_MEDIUM = colors.HexColor('#EAB308')
SEV_LOW = colors.HexColor('#3B82F6')
SEV_INFO = colors.HexColor('#6B7280')

PAGE_W, PAGE_H = A4
MARGIN = 18 * mm


def _sev_color(sev):
    s = (sev or '').upper()
    return {'CRITICAL': SEV_CRITICAL, 'HIGH': SEV_HIGH, 'MEDIUM': SEV_MEDIUM, 'LOW': SEV_LOW}.get(s, SEV_INFO)


def _risk_rating(score):
    if score is None:
        return 'N/A', COL_MUTED
    if score >= 7.0:
        return 'CRITICAL', SEV_CRITICAL
    if score >= 4.0:
        return 'HIGH', SEV_HIGH
    if score >= 2.0:
        return 'MEDIUM', SEV_MEDIUM
    if score > 0:
        return 'LOW', SEV_LOW
    return 'SECURE', colors.HexColor('#10B981')


def _fmt_dt(dt):
    if dt is None:
        return '--'
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.strftime('%d %b %Y, %H:%M UTC')


class _ShadowScanPageTemplate(PageTemplate):
    def __init__(self, doc):
        frame = Frame(
            MARGIN, MARGIN + 12 * mm,
            PAGE_W - 2 * MARGIN,
            PAGE_H - 2 * MARGIN - 22 * mm,
            id='body', leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0,
        )
        super().__init__('main', frames=[frame])

    def beforeDrawPage(self, canvas, doc):
        canvas.saveState()
        canvas.setFillColor(COL_BG)
        canvas.rect(0, 0, PAGE_W, PAGE_H, fill=1, stroke=0)
        band_h = 14 * mm
        canvas.setFillColor(COL_SURFACE)
        canvas.rect(0, PAGE_H - band_h, PAGE_W, band_h, fill=1, stroke=0)
        canvas.setStrokeColor(COL_CYAN)
        canvas.setLineWidth(1.5)
        canvas.line(0, PAGE_H - band_h, PAGE_W, PAGE_H - band_h)
        canvas.setFillColor(COL_CYAN)
        canvas.setFont('Helvetica-Bold', 11)
        canvas.drawString(MARGIN, PAGE_H - band_h + 4.5 * mm, 'ShadowScan')
        canvas.setFillColor(COL_MUTED)
        canvas.setFont('Helvetica', 9)
        canvas.drawRightString(PAGE_W - MARGIN, PAGE_H - band_h + 4.5 * mm, 'Vulnerability Scan Report')
        canvas.setStrokeColor(COL_BORDER)
        canvas.setLineWidth(0.5)
        canvas.line(MARGIN, MARGIN + 7 * mm, PAGE_W - MARGIN, MARGIN + 7 * mm)
        canvas.setFillColor(COL_MUTED)
        canvas.setFont('Helvetica', 7.5)
        canvas.drawString(MARGIN, MARGIN + 3 * mm, 'Generated by ShadowScan  |  Confidential')
        canvas.drawRightString(PAGE_W - MARGIN, MARGIN + 3 * mm, f'Page {doc.page}')
        canvas.restoreState()


def _build_styles():
    base = getSampleStyleSheet()

    def s(name, **kw):
        parent = kw.pop('parent', 'Normal')
        return ParagraphStyle(name, parent=base[parent], **kw)

    return {
        'report_title': s('report_title', fontSize=22, textColor=COL_TEXT, fontName='Helvetica-Bold', alignment=TA_CENTER, spaceAfter=4),
        'report_subtitle': s('report_subtitle', fontSize=10, textColor=COL_MUTED, fontName='Helvetica', alignment=TA_CENTER, spaceAfter=2),
        'section_heading': s('section_heading', fontSize=11, textColor=COL_CYAN, fontName='Helvetica-Bold', spaceBefore=6, spaceAfter=3),
        'body': s('body', fontSize=8.5, textColor=COL_TEXT, fontName='Helvetica', leading=12),
        'muted': s('muted', fontSize=7.5, textColor=COL_MUTED, fontName='Helvetica', leading=11),
        'cell': s('cell', fontSize=7.5, textColor=COL_TEXT, fontName='Helvetica', leading=10, wordWrap='LTR'),
        'cell_muted': s('cell_muted', fontSize=7, textColor=COL_MUTED, fontName='Helvetica', leading=10, wordWrap='LTR'),
        'label': s('label', fontSize=7, textColor=COL_MUTED, fontName='Helvetica-Bold', spaceAfter=1),
        'value': s('value', fontSize=9, textColor=COL_TEXT, fontName='Helvetica-Bold'),
        'notice': s('notice', fontSize=9, textColor=COL_MUTED, fontName='Helvetica-Oblique', alignment=TA_CENTER, spaceBefore=4, spaceAfter=4),
        'rec_item': s('rec_item', fontSize=8, textColor=COL_TEXT, fontName='Helvetica', leading=12, leftIndent=10, spaceAfter=3),
    }


class PdfReportService:
    def generate(self, scan, findings):
        buf = io.BytesIO()
        styles = _build_styles()
        doc = BaseDocTemplate(
            buf, pagesize=A4,
            leftMargin=MARGIN, rightMargin=MARGIN,
            topMargin=MARGIN + 14 * mm,
            bottomMargin=MARGIN + 12 * mm,
            title=f'ShadowScan Report - Scan #{scan.id}',
            author='ShadowScan',
        )
        doc.addPageTemplates([_ShadowScanPageTemplate(doc)])
        story = []
        story += self._build_cover(scan, styles)
        story += self._build_executive_summary(scan, findings, styles)
        story += self._build_severity_breakdown(findings, styles)
        story += self._build_findings_table(findings, styles)
        story += self._build_recommendations(scan, findings, styles)
        doc.build(story)
        return buf.getvalue()

    def _build_cover(self, scan, styles):
        now_str = _fmt_dt(datetime.now(timezone.utc))
        return [
            Spacer(1, 4 * mm),
            Paragraph('Vulnerability Scan Report', styles['report_title']),
            Paragraph(f'Scan #{scan.id}  |  Generated {now_str}', styles['report_subtitle']),
            Spacer(1, 3 * mm),
            HRFlowable(width='100%', thickness=1, color=COL_BORDER, spaceAfter=6 * mm),
        ]

    def _build_executive_summary(self, scan, findings, styles):
        story = [Paragraph('Executive Summary', styles['section_heading'])]
        rating_label, rating_color = _risk_rating(scan.risk_score)
        score_str = f'{scan.risk_score:.1f}' if scan.risk_score is not None else 'N/A'
        status_val = scan.status.value if hasattr(scan.status, 'value') else str(scan.status)
        meta_rows = [
            ('Target URL', scan.target_url),
            ('Scan ID', f'#{scan.id}'),
            ('Scan Status', status_val),
            ('Started', _fmt_dt(scan.created_at)),
            ('Completed', _fmt_dt(scan.completed_at)),
            ('Risk Score', f'{score_str} / 10.0'),
            ('Risk Rating', rating_label),
            ('Total Findings', str(len(findings))),
        ]
        col_w = PAGE_W - 2 * MARGIN
        label_w = col_w * 0.28
        value_w = col_w * 0.72
        table_data = [[Paragraph(r[0], styles['label']), Paragraph(r[1], styles['value'])] for r in meta_rows]
        tbl = Table(table_data, colWidths=[label_w, value_w])
        tbl.setStyle(TableStyle([
            ('ROWBACKGROUNDS', (0, 0), (-1, -1), [COL_SURFACE, COL_BG]),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.4, COL_BORDER),
            ('TEXTCOLOR', (1, 6), (1, 6), rating_color),
        ]))
        story += [tbl, Spacer(1, 6 * mm)]
        return story

    def _build_severity_breakdown(self, findings, styles):
        story = [Paragraph('Severity Breakdown', styles['section_heading'])]
        counts = {'CRITICAL': 0, 'HIGH': 0, 'MEDIUM': 0, 'LOW': 0, 'INFO': 0}
        for f in findings:
            sev = (f.severity.value if hasattr(f.severity, 'value') else str(f.severity)).upper()
            if sev in counts:
                counts[sev] += 1
            else:
                counts['INFO'] += 1
        col_w = (PAGE_W - 2 * MARGIN) / 5
        sev_cols = [SEV_CRITICAL, SEV_HIGH, SEV_MEDIUM, SEV_LOW, SEV_INFO]
        sev_labels = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO']
        header = [Paragraph(lbl, ParagraphStyle(f'sh_{lbl}', fontSize=7, textColor=c, fontName='Helvetica-Bold', alignment=TA_CENTER)) for lbl, c in zip(sev_labels, sev_cols)]
        values = [Paragraph(str(counts[lbl]), ParagraphStyle(f'sv_{lbl}', fontSize=18, textColor=c, fontName='Helvetica-Bold', alignment=TA_CENTER)) for lbl, c in zip(sev_labels, sev_cols)]
        tbl = Table([header, values], colWidths=[col_w] * 5)
        tbl.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), COL_SURFACE),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 0.4, COL_BORDER),
            ('LINEABOVE', (0, 0), (-1, 0), 2, COL_CYAN),
        ]))
        story += [tbl, Spacer(1, 6 * mm)]
        return story

    def _build_findings_table(self, findings, styles):
        story = [Paragraph('Vulnerability Findings', styles['section_heading'])]
        if not findings:
            story.append(Paragraph('No vulnerabilities were detected during this scan.', styles['notice']))
            story.append(Spacer(1, 4 * mm))
            return story
        col_w_total = PAGE_W - 2 * MARGIN
        col_widths = [col_w_total * 0.09, col_w_total * 0.11, col_w_total * 0.17, col_w_total * 0.31, col_w_total * 0.32]
        hdr_style = ParagraphStyle('th', fontSize=7, textColor=COL_CYAN, fontName='Helvetica-Bold', alignment=TA_LEFT)
        header_row = [Paragraph(h, hdr_style) for h in ['Severity', 'Plugin', 'Title', 'Description', 'Recommendation']]
        table_data = [header_row]
        row_cmds = []
        for idx, f in enumerate(findings, start=1):
            sev_str = (f.severity.value if hasattr(f.severity, 'value') else str(f.severity)).upper()
            sev_col = _sev_color(sev_str)
            sev_ps = ParagraphStyle(f'sev_{idx}', fontSize=7, textColor=sev_col, fontName='Helvetica-Bold', alignment=TA_CENTER)
            row = [
                Paragraph(sev_str, sev_ps),
                Paragraph(f.plugin or '-', styles['cell_muted']),
                Paragraph(f.vulnerability_name or '-', styles['cell']),
                Paragraph(f.description or '-', styles['cell_muted']),
                Paragraph(f.recommendation or '-', styles['cell_muted']),
            ]
            table_data.append(row)
            bg = COL_SURFACE if idx % 2 == 0 else COL_BG
            row_cmds.append(('BACKGROUND', (0, idx), (-1, idx), bg))
        tbl = Table(table_data, colWidths=col_widths, repeatRows=1)
        base_cmds = [
            ('BACKGROUND', (0, 0), (-1, 0), COL_SURFACE),
            ('LINEBELOW', (0, 0), (-1, 0), 1, COL_CYAN),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 0.3, COL_BORDER),
            ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ]
        tbl.setStyle(TableStyle(base_cmds + row_cmds))
        story += [tbl, Spacer(1, 6 * mm)]
        return story

    def _build_recommendations(self, scan, findings, styles):
        story = [
            HRFlowable(width='100%', thickness=0.5, color=COL_BORDER, spaceBefore=2 * mm, spaceAfter=4 * mm),
            Paragraph('Security Recommendations', styles['section_heading']),
        ]
        status_val = scan.status.value if hasattr(scan.status, 'value') else str(scan.status)
        if status_val in ('PENDING', 'RUNNING'):
            story.append(Paragraph('This scan is still in progress. Recommendations will be available once it completes.', styles['notice']))
            return story
        if status_val == 'FAILED':
            story.append(Paragraph('This scan encountered an error and did not complete. Please re-run the scan.', styles['notice']))
            return story
        if not findings:
            story.append(Paragraph('No vulnerabilities detected. Continue monitoring and keep all software up to date.', styles['notice']))
            return story
        sev_order = {'CRITICAL': 0, 'HIGH': 1, 'MEDIUM': 2, 'LOW': 3}
        sorted_findings = sorted(findings, key=lambda f: sev_order.get((f.severity.value if hasattr(f.severity, 'value') else str(f.severity)).upper(), 4))
        seen_recs = set()
        for f in sorted_findings:
            rec = (f.recommendation or '').strip()
            title = f.vulnerability_name or 'Unknown vulnerability'
            sev_str = (f.severity.value if hasattr(f.severity, 'value') else str(f.severity)).upper()
            if not rec or rec in seen_recs:
                continue
            seen_recs.add(rec)
            bullet_text = f'<b>[{sev_str}]</b>  <b>{title}</b> - {rec}'
            story.append(Paragraph(bullet_text, styles['rec_item']))
        story.append(Spacer(1, 4 * mm))
        return story