"""sync_cascades_and_types

Revision ID: 547b7d7f1f56
Revises: 9c2f8e12ab34
Create Date: 2026-08-26 20:19:57.803276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '547b7d7f1f56'
down_revision: Union[str, Sequence[str], None] = '9c2f8e12ab34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type if it does not exist
    verification_purpose_enum = postgresql.ENUM('EMAIL_VERIFICATION', 'PASSWORD_RESET', name='verificationpurpose')
    verification_purpose_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('email_verifications', 'purpose',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', name='verificationpurpose'),
               postgresql_using='purpose::verificationpurpose',
               existing_nullable=False)
    op.alter_column('email_verifications', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('email_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('email_verifications_user_id_fkey'), 'email_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'email_verifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('findings_scan_id_fkey'), 'findings', type_='foreignkey')
    op.create_foreign_key(None, 'findings', 'scans', ['scan_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('scans_user_id_fkey'), 'scans', type_='foreignkey')
    op.create_foreign_key(None, 'scans', 'users', ['user_id'], ['id'], ondelete='CASCADE')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.create_foreign_key(op.f('scans_user_id_fkey'), 'scans', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.create_foreign_key(op.f('findings_scan_id_fkey'), 'findings', 'scans', ['scan_id'], ['id'])
    op.drop_constraint(None, 'email_verifications', type_='foreignkey')
    op.create_foreign_key(op.f('email_verifications_user_id_fkey'), 'email_verifications', 'users', ['user_id'], ['id'])
    op.alter_column('email_verifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('email_verifications', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('email_verifications', 'purpose',
               existing_type=sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', name='verificationpurpose'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
